version: '3.8'

services:
  neo4j:
    build:
      context: ./neo4j
    #image: 'neo4j:latest'
    environment:
      - NEO4J_browser_post__connect__cmd=guide intro;play ${ALZ_URL}/${ALZ_ABOUT};play ${ALZ_URL}/${ALZ_SAMPLES}
      - NEO4J_read__only=true
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_http_enabled=true
      - NEO4J_dbms_connector_https_enabled=false
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
    #tty: true
    volumes:
      - '/data/neo4j/data:/var/lib/neo4j/data'
      - '/data/neo4j/logs:/var/lib/neo4j/logs'
      - '/data/neo4j/import:/var/lib/neo4j/import'
      - '/data/neo4j/plugins:/var/lib/neo4j/plugins'
      - '/data/neo4j/dumps:/var/lib/neo4j/dumps'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
